import type { Metadata } from "next";
import "./globals.css";
import NavMain from "@/components/navbar/mainNavbar/NavMain";
import { StoreProvider } from "@/state/StoreProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className="font-body">
          <NavMain />
          {children}
        </body>
      </html>
    </StoreProvider>
  );
}
